project:
  type: website
  output-dir: docs
  resources: 
    - CNAME
    - overleaf_presentations

website:
  title: "Evanns Morales-Cuadrado |<br>
          Research Website"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv
        text: CV
      - href: publications
        text: Publications
      - href: blog
        text: Blog
      - href: about
        text: About Me
  # twitter-card: true
  # open-graph: true

  

format:
  html:
    theme: lux
    css: styles.css
    # toc: true
    html-math-method: mathjax



